# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-01 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manyb',
            name='manya',
            field=models.ManyToManyField(to='mytest.ManyA'),
        ),
    ]
