# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-07 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_content_html'),
        ('comment', '0002_auto_20190505_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ManyToManyField(to='blog.Post', verbose_name='文章'),
        ),
    ]
